# fly.toml app configuration file generated for sos-helmet-api on 2025-08-20T16:30:18+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sos-helmet-api'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
