# fly.toml app configuration file generated for sos-helmet-api on 2025-08-20T16:30:18+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# fly.toml app configuration file
app = 'sos-helmet-api'
primary_region = 'fra'

# Questa sezione dice a Fly.io come avviare il tuo server.
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

# Questa sezione definisce il comando per il processo 'app'
[processes]
  app = 'npm run start'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb' # Aggiungiamo questo per essere sicuri di rimanere nel piano gratuito